title: Felix Jan Nitsch # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  
  Hic rhodos, hic salta!<br>

  ____<br><br>

  <a href="/files/CV.pdf">CV</a>
  <br>
  
  <a href="publications.html">Publications</a>
  <br>

  <a href="https://www.linkedin.com/in/fjnitsch/">LinkedIn</a>
  <br>

  <a href="https://bsky.app/profile/felixjannitsch.bsky.social">BlueSky</a>
  <br>

  ____

theme: jekyll-theme-minimal
google-analytics: "G-V1QVKG4ENS"