---
title: "Resumé of 'Open Neuroscience & Psychology'"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
data <- readxl::read_excel('How did you like "Open Neuroscience & Psychology"? (Antworten).xlsx')
```

August 11, 2021

<br>

**During the last year (#corona), I have taught 4-week online course on open science in the fields of neuroscience and psychology. In an attempt to fully utilize the online teaching format, I utilized various channels of communication such as [YouTube-Videos](https://youtube.com/playlist?list=PLA4sf7DGYk9kjMwpVCk3cfIHZi33JBC51), interactive WebEx-Sessions, media- and research articles, brief presentations, and an essay project. As of this winter, I will no longer be able to teach the course (news coming soon). Hence, with this blog post, I want to provide a quick wrap-up of the students' evaluations, my own experiences and the future of the course.**

<br><br>

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLA4sf7DGYk9kjMwpVCk3cfIHZi33JBC51" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br><br>

## The Motivation

The design of this course was motivated by two reasons: 

First, the necessity. The pandemic forced university lecturers to adapt their curricula to a completely online-based format, me no exception. My previous curriculum, a practical introduction to stress research, proved to be particularly unsuitable for this endeavour. Due to ethical and resource constraints, it was already difficult to convey a legitmate *practical* experience of stress research in-person. Forcing the curriculum into an online format would, therefore, have only been a cheap compromise. 

Second, the opportunity. With the rise of increasing scepticism in the trustworthiness of science and scandals of reknown professors committing fraud, it seemed absolutely necessary to me, to address concerns and remedies of questionable research practice. And, while I see myself only as an enthusiast and a trying practicioner of open science, given the lack of other explicit course on the topic in our psychology curriculum I wanted to start with *something*.

<br>

>"Can people sense the future? Does a frozen salmon have emotions? False research findings are published even in respected academic journals. The fields of neuroscience and psychology suffer from questionable statistics, inaccurate reporting, insufficient methodological rigor and lack of transparency."

<br>

## The Reception

In order, to understand the student perspective and experience of the course, I conducted a quick google survey. Of in total about 70 students, 34 provided voluntary, anononymus feedback. Answers were always provided on a 5-point Likert-scale with the anchor values 1 = "Not at all" and 5 = "Very much". Results are shown below. 

### Videos

![The videos received a mean rating of **M = `r round(mean(unlist(data[,2])), 2)`** (Range = `r min(unlist(data[,2]))` - `r max(unlist(data[,2]))`).](OpenSciEval/Slide1.png)

### WebEx Sessions

![The WebEx sessions received a mean rating of **M = `r round(mean(unlist(data[,3])), 2)`** (Range = `r min(unlist(data[,3]))` - `r max(unlist(data[,3]))`).](OpenSciEval/Slide2.png)

### Assignments

![The assigments (creating short presentations) received a mean rating of **M = `r round(mean(unlist(data[,4])), 2)`** (Range = `r min(unlist(data[,4]))` - `r max(unlist(data[,4]))`).](OpenSciEval/Slide3.png)

### Reading

![The selection of articles to read received a mean rating of **M = `r round(mean(unlist(data[,5])), 2)`** (Range = `r min(unlist(data[,5]))` - `r max(unlist(data[,5]))`).](OpenSciEval/Slide4.png)

### Essay

![The essay project received a mean rating of **M = `r round(mean(unlist(data[,6]), na.rm = T), 2)`** (Range = `r min(unlist(data[,6]), na.rm = T)` - `r max(unlist(data[,6]), na.rm = T)`).](OpenSciEval/Slide5.png)

### My performance

![My performance as instructor received a mean rating of **M = `r round(mean(unlist(data[,7])), 2)`** (Range = `r min(unlist(data[,7]))` - `r max(unlist(data[,7]))`).](OpenSciEval/Slide6.png)

### Overall

![Overall, the course received a mean rating of **M = `r round(mean(unlist(data[,8])), 2)`** (Range = `r min(unlist(data[,8]))` - `r max(unlist(data[,8]))`).](OpenSciEval/Slide7.png)

### Freetext Feedback

Lastly, I received many positive responses a freetext feedback,
of which I want to share a few selected ones (translated to English via DeepL):

<br>

>The course was very interesting, definitely one of the most exciting and current topics in the entire Bachelor. Thank you for it!

>I really liked the variety of ways you used to convey information (YouTube videos, articles, WebEx, Menti).  It also made the self-study and assignment work much more engaging, interesting and motivating.  Overall, I found the workload (reading articles, watching videos, creating assignments, WebEx sessions and essay as examination performance) quite high, but not overwhelming. However, I would have preferred not to receive the topic for the essay only one week before submission, so that the processing time would not be so short and one could already think about it and collect ideas during the course. In general, the atmosphere in the course (although it was online) was pleasant and constructive. So, overall, I found the course very good and I feel that I was able to take something away with me. Many thanks

>I found it really great that we always got constructive feedback on our presentations and lectures. I was also very motivated when you praised me. In addition, you were the first person to think about our life-work balance and to accommodate us, especially during the online lecture and learning phase, and to encourage us to still keep regular learning and working hours. I found that really good and helpful! Apart from that, it was really great that we had the opportunity to try out the lectures, especially since it was still a bit of a challenge in English. Because it was ungraded, there was no pressure and we had a chance to improve. The Zoom meetings in general were also always well moderated and designed! Overall, I found the course very interesting and am very glad that I chose it.

## The Future

As mentioned in the beginning, I will not be able to continue teaching the course in the upcoming winter-semester (news coming soon). I really much enjoyed working with the students and am glad that the invested efforts seems to have paid off. I have learned a lot about open science in the preparation of the curriculum and the discussions with the students were very productive and often made me realize new insights. I am most definitely going to miss this! Fortunately, at least for the next the semester, the concept and framework of the open science seminar will be continued by a colleague of mine.